# Generated by Django 4.2.7 on 2023-11-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_remove_deck_container_deck_user_alter_card_deck_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
    ]
